### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tonadev** [sugarlabs/Bounce#12]
### Explanation
When running ```sugar-activity```, I got this:
```
tonadev@TDPC:~/Documents/Work/OpenSource/code_in/sugarlabs/Bounce$ sugar-activity
Segmentation fault (core dumped)
```
And yeah it was before I did changes.

### Cause:
After commenting this line, I could proceed working.
```
from pongc import *
```

### OS
* Ubuntu 18.04

**Comment by quozl** [comment]
Reproduced.  Also an `import gtk` does fail, `ImportError: No module named gtk`.

Expected.  It is a GTK+ 2 Sugar activity, and Ubuntu 18.04 dropped support for GTK+ 2 Sugar activities.  You can try Ubuntu 16.04 up to 17.10, or build `sugar-toolkit` using Ubuntu source packages that were removed from their archive prior to 18.04 release.

Will be fixed by https://github.com/sugarlabs/Bounce/issues/7, so closing this as a duplicate.  Further discussion welcome though.

**Comment by tonadev** [comment]
@quozl Yeah! I'm working on it. But when porting to Gtk3 that's the error I get. As I said before this line
```
from pongc import *
```
 Is causing it.

**Comment by quozl** [comment]
```
gdb python
(gdb) run /usr/bin/sugar-activity
(gdb) bt
```

Tells me the failure is in `dlopen`, so the `pongc` binaries are incompatible with your system and would need to be rebuilt.  See `INSTALL` for how to do that.  The binaries are compiled from a C++ source file.

Activities that embed binaries instead of using only Python source often fail when tried on new operating system builds.  We don't recommend using binaries, but some insisted on doing so.
