### ISSUE TITLE
WARNING:root:Missing po/ dir, cannot build_locale

### ISSUE THREAD

**Issue by vipulgupta2048** [sugarlabs/Bounce#9]
The warning comes up when running `setup.py` with the argument `dist_xo` or `build`

**Comment by quozl** [comment]
It's not an error, it's a warning.  It does not affect the outcome of the `dist_xo` step; the .xo bundle is created, and the exit status is zero.  The warning is from the toolkit because the activity does not have internationalisation setup, even though it imports and uses gettext.  https://translate.sugarlabs.org/ has no project entry for Bounce.  You can work around the warning with
```bash
mkdir po
python setup.py genpot
```

**Comment by vipulgupta2048** [comment]
Yes, it's a warning indeed. I was thinking we should mark it down for translations? I am informed about the purpose of po/ and the internalization setup.

**Comment by quozl** [comment]
I don't understand, sorry.  That the warning comes up is not an issue because it is expected.  If you want to enable the activity for internationalisation support, you don't need any permission or discussion do you?  Investigate and make a pull request.
